delete from vlog_post where `id` NOT IN ('60', '59', '2');
delete from vlog_comment where `pid` NOT IN ('60', '59', '2') and `type`='0' and `id` NOT IN ('24');
update vlog_comment set `pid`='393' where `id`='24';
delete from vlog_post_to_tag where `pid` NOT IN ('60', '59' '2');
delete from vlog_post_to_category where `pid` NOT IN ('60', '59', '2');
update vlog_post set `id`='560' where `id`='60';
update vlog_post set `id`='549' where `id`='59';
update vlog_post set `id`='502' where `id`='2';
update vlog_comment set `pid`='560' where `pid`='60';
update vlog_comment set `pid`='549' where `pid`='59';
update vlog_comment set `pid`='502' where `pid`='2';
update vlog_post_to_tag set `pid`='560' where `pid`='60';
update vlog_post_to_tag set `pid`='549' where `pid`='59';
update vlog_post_to_tag set `pid`='502' where `pid`='2';
update vlog_post_to_category set `pid`='560' where `pid`='60';
update vlog_post_to_category set `pid`='549' where `pid`='59';
update vlog_post_to_category set `pid`='502' where `pid`='2';
